### PR TITLE
Restructure & Added Bootstrap

### PR DESCRIPTION
**Pull request by ascii-dev**

### CODE REVIEW

**Comment by bgub** [comment]
Thanks! Before I merge this, can you enable Github Pages on your fork so in the future we can preview?

**Comment by ascii-dev** [comment]
Sure... I'll update you once I'm able to do that.

**Comment by ascii-dev** [comment]
Hey, I've enabled Github pages and it's linked here https://ascii-dev.github.io/awesome-for-beginners/. There's presently no view on the index.html, just pulled in Bootstrap and rearranged the file structure for now. Will start working on something soon enough...

**Comment by bgub** [comment]
Thanks!

**Pull request merged**
